# =========================================================
# Kitty — low latency + smooth cursor + tmux friendly
# =========================================================

# ----- Window -----
background_opacity 0.9
hide_window_decorations yes
window_padding_width 0
enable_audio_bell no
confirm_os_window_close 0

# ----- Font -----
font_family monospace
bold_font monospace Bold
italic_font monospace Italic
font_size 10.0

disable_ligatures never

# ----- Colors -----
background #171421
foreground #cdd6f4

cursor_text_color #FFFFFF
cursor            #EB5B0F

selection_foreground #1e1e2e
selection_background #f5c2e7

# ----- Performance / Smoothness -----
input_delay 0
repaint_delay 2
sync_to_monitor yes

# Cursor trail
cursor_trail 2
cursor_trail_decay 0.06 0.22

# Cursor blink
cursor_blink_interval 0.5
cursor_stop_blinking_after 0

# Rendering
linux_display_server auto
wayland_enable_ime no

# Faster resize redraws
resize_draw_strategy scale

# Reduce visual stutter
dynamic_background_opacity yes

# ----- Scrolling -----
wheel_scroll_multiplier 5.0
touch_scroll_multiplier 5.0

# ----- Shell -----
shell /bin/bash --login

# ----- Clipboard -----
copy_on_select yes

# ----- Misc -----
shell_integration enabled
