[general]
import = [
  # Uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml",
  # "~/.config/alacritty/catppuccin-frappe.toml",
  # "~/.config/alacritty/catppuccin-macchiato.toml",
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
opacity = 0.9
decorations = "none"
padding = { x = 2, y = 0 }

[font]
normal = { family = "FiraCode Nerd Font", style = "Medium" }
size = 10.0

[colors.primary]
background = "#171421"
foreground = "0xcdd6f4"

[colors.cursor]
text = "0x1e1e2e"
cursor = "0xff0077"

[colors.selection]
text = "0x1e1e2e"
background = "0xf5c2e7"

[terminal.shell]
program = "/bin/bash"
args = ["--login"]
